app:
    resource: "@AppBundle/Controller/"
    prefix: /
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
